[workspace]
members = [
  "contracts/water-well-initiative",
  "contracts/citizen-science-registry",
  "contracts/utility-water-footprint",
  "contracts/sustainable-action-rewards",
  "contracts/community-bounty",
  "contracts/water-credit-marketplace",
  "contracts/local-dao",
  "contracts/cross-platform-exchange",
]
resolver = "3"

[workspace.package]
edition = "2024"
